### PR TITLE
Remove android offset

### PR DESCRIPTION
**Pull request by hannesmcman**
We've been using this Popover component in our app and have noticed that the popover arrow is vertically misaligned on android. This PR aims to fix that.

Before | After
-- | --
screen shot 2018-08-12 at 9 55 19 pm | screen shot 2018-08-12 at 9 52 14 pm

### CODE REVIEW

**Comment by SteffeyDev** [comment]
What versions of Android have you tested? I added the offset because the device I was testing on was offset for some reason, but I think it was an older version of Android. I’m worried that if I commit this, it may break on certain versions. If you can let me know what versions you have tested on, and I can test on a few versions, maybe we can figure this out.

**Comment by SteffeyDev** [comment]
Also my apologies for not getting back sooner, it’s been a busy week.

**Comment by rye** [comment]
@SteffeyDev, this PR fixes the issue we had in StoDevX/AAO-React-Native#2764, which was that on my phone (a OnePlus 3, running Android 8.0.0) our popover was over the top of a button—this is what inspired this PR.

<details><summary>Screenshot</summary></details>

I just tested and it looked fine on this device.

**Comment by SteffeyDev** [comment]
@rye I understand that your fix works well on that specific device running that specific version of Android, but hopefully you can understand that among the thousands of Android devices that this library should run on, that is not sufficient testing. I’d love to figure out exactly which versions are effected so that we can do a version check and toggle the offset as needed. Do you have any method of helping me test this or additional devices you can check on?

**Comment by SteffeyDev** [comment]
Ok, thanks for doing the testing!  I feel more comfortable now removing it by default.  However, for some reason my Expo test app still needs the offset to work (not sure what Expo + RN is doing in the backend), so I went ahead and made the change myself but added a `verticalOffset` prop, so that apps that need the offset on Android can still use it.  I will publish 1.0.4 tonight.  Thanks for bringing this to my attention!

**Comment by SteffeyDev** [comment]
Alright @rye should be live now on NPM

**Comment by rye** [comment]
Awesome, thanks!

**Comment by dev-fuad** [comment]
Ok so if anyone is facing this issue of having extra space between anchor(button) and popover arrow in android
This may be because you might be using translucent status bar (which is default in expo, @SteffeyDev's case) then you need this vertical offset (`= StatusBar.currentHeight`).

**Pull request closed without merging**
