### PR TITLE
kevin/animation-fix

### PR DESCRIPTION
**Pull request by kev71187**
https://github.com/SteffeyDev/react-native-popover-view/issues/55

### CODE REVIEW

**Comment by SteffeyDev** [comment]
What happened with and without using the dynamic value for FIX_SHIFT?

**Comment by SteffeyDev** [comment]
The value should have been arbitrary, I just needed to make sure it was larger than the screen so it didn’t show.

**Comment by kev71187** [comment]
To be honest, I am not sure if the FIX_SHIFT causes problems; just fixed it because the calculation would be wrong when the device rotates. I can remove.

**Comment by kev71187** [comment]
The set timeout fix is also not a perfect fix as it is still feasible the secondary event could come in after the the timeout, but significantly reduces the occurrence. Wasn't able to track down the exact cause of the double layout onChange event

**Comment by SteffeyDev** [comment]
Ok, if you remove the FIX_SHIFT change I will merge

**Comment by kev71187** [comment]
sorry for the delay, should be all cleaned up

**Pull request merged**
