### PR TITLE
Changed the popover props

### PR DESCRIPTION
**Pull request by nicomontanari**
The prop "isVisible" must not be optional, while "arrowShift" must be optional.

### CODE REVIEW

**Review by SteffeyDev — CHANGES_REQUESTED** [review]
isVisible should be optional, see Readme for examples. Please remove that change and I will merge to fix arrowShift.

**Comment by nicomontanari** [comment]
I made these changes following the props table and the prop isVisible is with attribute optional as "No".
Do I have to change the README too?

**Comment by SteffeyDev** [comment]
Ah good catch, I missed updating that on the Readme when I released v3. If you don't update it I will before I release.

**Comment by nicomontanari** [comment]
Now everything looks fine 😄

**Pull request merged**
